Ex 1
graag/practicepython_as pull request #1
Opened 2022-01-27 12:11 UTC by aldonaspirz

Zrobione podstawowe algorytmy bez Extras

Wykorzystane biblioteki: random, BeautifulSoup

Do dokończenia (piątek 28.01): argparse, json

2022-02-11 10:59 UTC, graag requested changes
Ogólnie wygląda bardzo fajnie.

Dodałem szczegółowe komentarze i uwagi do poszczególnych kawałków.

2022-02-11 10:59 UTC, graag commented on Ex_1.py
> +if data==None:
Przy porównaniu z None stosujemy `is`:

`if data is None:`

Zgodnie z https://www.python.org/dev/peps/pep-0008/#programming-recommendations

2022-02-11 10:59 UTC, graag commented on Ex_1.py
> +    with open(args.f, 'r') as f:
Dodaj obsługę https://docs.python.org/3/library/exceptions.html#FileNotFoundError

2022-02-11 10:59 UTC, graag commented on Ex_1.py
> +if data==None:
Odnosi się oczywiście do pozostałych excericises

2022-02-11 10:59 UTC, graag commented on Ex_11.py
> +    return int(input("Give me a number: "))
Dodaj obsługę przypadku gdy ktoś poda coś innego niż liczbę

2022-02-11 10:59 UTC, graag commented on Ex_11.py
> +    for x in range(2, a):
Zastanów się czy musisz sprawdzać wszystkie liczby od 2 do a ...

2022-02-11 10:59 UTC, graag commented on Ex_13.py
> +        a, b = b, a+b
Fajne rozwiązanie :)

2022-02-11 10:59 UTC, graag commented on Ex_13.py
> +        i=+1
??? Czemu zwiększasz `i`

2022-02-11 10:59 UTC, graag commented on Ex_13.py
> +    n=int(input("how many Fibonnaci numbers to generate?"))
Dodaj obsługe przypadku gdy podana liczba nie jest liczbą lub jest mniejsza niż 1

2022-02-11 10:59 UTC, graag commented on Ex_10.py
> +    c=[x for x in set(a) if x in (a and b) ]
To działa ale nie tak jak sądzisz :)
```
In [1]: a = [1,2]

In [2]: b = [3,4]

In [3]: a and b
Out[3]: [3, 4]
```

Czyli `a and b` zwraca po prostu `b`. Tak na prawdę to co napisałaś wygląda tak:

```
c=[x for x in set(a) if x in b ]
```

Sumowanie list jest możliwe:
```
In [5]: a + b
Out[5]: [1, 2, 3, 4]
```

Rozwiązanie z list comprehension gdzie wstawiamy dodatkowy filtr w postaci `if x in b` jest bardzo wolne:

```
In [17]: a = [random.randrange(1, 500, 1) for i in range(1000)]

In [18]: b = [random.randrange(1, 500, 1) for i in range(2000)]

In [19]: timeit.timeit("c=list(set(a).intersection(b))", globals = globals())
Out[19]: 48.15213498599769

In [20]: timeit.timeit("c=[x for x in set(a) if x in b ]", globals = globals())
Out[20]: 956.6210397600007
```

Szybszym rozwiązaniem jest oparcie się całkowicie na typie set:
```
c = list( set(a).intersection(b) )
```

2022-02-11 10:59 UTC, graag commented on Ex_14.py
> +    return list(new_list)
Jak byś to napisała bez użycia `set`?

2022-02-11 10:59 UTC, graag commented on Ex_15.py
> +        c=b[::-1]
+1

2022-02-11 10:59 UTC, graag commented on Ex_16.py
> +def new_password(characters):
Dodaj mozliwość określenia długości hasła

2022-02-11 10:59 UTC, graag commented on Ex_16.py
> +    new=random.sample(characters,10)
Co jeśli chcielibyśmy mieć hasło bez powtarzających się znaków?

2022-02-11 10:59 UTC, graag commented on Ex_17.py
> +#Rozwiązanie znalezione, nie autorskie
:)

2022-02-11 10:59 UTC, graag commented on Ex_17.py
> +import urllib.request
Proponuję używać https://docs.python-requests.org/en/latest/

2022-02-11 10:59 UTC, graag commented on Ex_2.py
> +    number=int(input('Podaj liczbę'))
Dodaj obsługe blędnie podanej liczby

2022-02-11 10:59 UTC, graag commented on Ex_4.py
> +    for i in range(1,a+1):
Zastanów się czy musisz sprawdzać aż do a+1

2022-02-11 10:59 UTC, graag commented on Ex_5.py
> +    print(set(a).intersection(b))
Miałem zapytać jak to zrobić bez set ale jest to w Ex10

2022-02-11 10:59 UTC, graag commented on Ex_7.py
> +    c=[x for x in a if x %2== 0]
Staraj się nie powtarzać kodu.

Albo przygotuj dane w tym samym formacie wcześniej. Albo użyj funkcji.

2022-02-11 10:59 UTC, graag commented on Ex_8.py
> +    a=str(input("Rock,Scissors,Paper?"))
Dodaj obsługę błędnego inputu

2022-02-11 10:59 UTC, graag commented on Ex_8.py
> +        elif a=='Rock' and b=='Scissors':
Jak można by to napisać bardziej generycznie? Jak przedstawiłabyś kamień, norzyce i papier numerycznie i zastosowała operator mniejszy/większy między liczbami?

2022-02-11 10:59 UTC, graag commented on Ex_9.py
> +# Keep track of how many guesses the user has taken, and when the game ends, print this out.
Brak zliczania liczby prób

2022-02-11 10:59 UTC, graag commented on Ex_9.py
> +        a=randrange(1,10)
Nie pozwalasz zgadnąć liczby. Losując za każdym razem nową nie pozwalasz na zabawę ciepło/zimno

2022-02-14 18:03 UTC, graag commented on Ex_10.py
> +try:
To już zostawmy jak jest.

Na przyszłość staraj się ustawiać bloki try + except tak by zawierały tylko ten kod gdzie spodziewasz się błędu i chcesz go obsłużyć.

W tym wypadku:
```
if args.f:
    try:
        with open(args.f, 'r') as f:
            data = json.load(f)
    except OSError as e:
        print(e)
```

Zauważ że gdy łapiesz wyjątek i go wypisujesz w ten sposób nie jest wyświetlany traceback. Można go wypisać jeśli jest potrzebny (czasami nazwa wyjątku mało mówi ...):
```
import traceback

if args.f:
    try:
        with open(args.f, 'r') as f:
            data = json.load(f)
    except OSError as e:
        traceback.print_exc()
```

Oczywiście są wyjątki od tej zasady i czasami stosujemy bloki "catch all" gdzie łapiemy wszystkie możliwe wyjątki :)

2022-02-16 08:43 UTC, graag commented on Ex_8.py
> +        if a=='Rock' or a=='Scissors' or a=='Paper' and b=='Rock' or b=='Scissors' or b=='Paper':
```
valid_inputs = ['Rock','Paper','Scissors']

if a in valid_inputs and b in valid_inputs:
```

2022-02-16 08:44 UTC, graag commented on Ex_8.py
> +                c=dict()
Macierz stanów - fajne :)

2022-02-16 08:46 UTC, graag commented on Ex_13.py
> +    n=int(input("how many Fibonnaci numbers to generate?"))
Miało być jeszcze
try:
    n=int(input("bla bla"))
except ValueError:
    print("Wprowadzone dane nie są liczbą")

2022-02-18 10:10 UTC, aldonaspirz commented
@graag poprawki wprowadzone

2022-02-23 09:45 UTC, graag commented
Super. Robię merge

2022-02-23 09:45 UTC, merged